name: build

on:
  pull_request:
    branches:
      - 'develop'
  push:
    paths:    
      - '**'
      - '!package.json'
      - '!CHANGELOG.md'     
    branches:
      - 'develop'
      - 'feature/*'
      - 'bug/*'

jobs:
    
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v1

      - name: cache directory
        id: npm-cache
        run: |
          echo "::set-output name=npm_cache_directory::$(npm config get cache)"
      - name: cache
        id: cache
        uses: actions/cache@v1.0.3
        with:
          path: ${{ steps.npm-cache.outputs.npm_cache_directory }} # ~/.npm # Cache Examples: https://github.com/actions/cache/blob/master/examples.md
          key: npm-cache-${{ runner.OS }}-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
          restore-keys: |
            npm-cache-${{ runner.OS }}-build
            npm-cache-${{ runner.OS }}-
            npm-cache-
      - name: ci
        id: ci
        shell: pwsh
        # if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: lint
        id: lint
        shell: pwsh
        run: npm run lint

      - name: test
        id: test
        shell: pwsh
        if: github.event_name == 'pull_request'
        run: |
          npm test
      - name: build
        id: build
        shell: pwsh
        run: |
          npm run build
      - name: archive
        id: archive
        if: github.event_name != 'pull_request'
        shell: pwsh
        run: |
          Compress-Archive -Path dist/resume/* -DestinationPath dist/resume/resume.zip
      
      - name: upload
        id: upload
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@master
        with:
          name: drop
          path: dist/resume/resume.zip        

      - name: release
        id: release
        if: github.ref == 'refs/heads/develop'
        shell: pwsh
        run: |
          npm run release
          
      - name: display
        id: display
        if: github.ref == 'refs/heads/develop'
        shell: pwsh
        run: |
          ${{ env.release_tag }}    
