name: commit-lint

on:
  pull_request:
    branches:
      - develop

jobs:
  
  lint:
    name: lint
    runs-on: ubuntu-latest        
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
    
      - name: checkout
        uses: actions/checkout@master
        
      - name: lint




        uses: wagoid/commitlint-github-action@v1.2.3




        with:
          configFile: ./.commitlintrc.json
