name: release

on:
  release:
    types: [published]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      
jobs:
  release:
    runs-on: ubuntu-latest    
      
    steps:
      - name: download
        id: download
        shell: pwsh 
        run: |
          $releaseUrl = 'https://api.github.com/repos/$env:GITHUB_REPOSITORY/releases/tags/$env:GITHUB_REF'
          $gitHubRelease = (Invoke-WebRequest -Uri $releaseUrl -Method Get -ContentType 'application/json' -Headers @{'Authorization' = 'Bearer $env:GITHUB_TOKEN'}).Content | ConvertFrom-Json
          Invoke-WebRequest -Uri $gitHubRelease.assets[0].browser_download_url -OutFile $gitHubRelease.assets[0].name
          Expand-Archive -LiteralPath $gitHubRelease.assets[0].name -DestinationPath $gitHubRelease.assets[0].name.Split('.')[0]

      - name: deploy
        id: deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          BRANCH: master
          FOLDER: resume
