name: release

on:
  push:
    tags:        
      - 'v*.*.*'
#on:
#  release:
#    types: [published]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      
jobs:
  release:
    runs-on: ubuntu-latest    
      
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@master

      - name: cache directory
        id: npm-cache
        run: |
          echo "::set-output name=npm_cache_directory::$(npm config get cache)"

      - name: cache
        id: cache
        uses: actions/cache@v1.0.3
        with:
          path: ${{ steps.npm-cache.outputs.npm_cache_directory }} # ~/.npm # Cache Examples: https://github.com/actions/cache/blob/master/examples.md
          key: npm-cache-${{ runner.OS }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-${{ runner.OS }}-build
            npm-cache-${{ runner.OS }}-
            npm-cache-

      - name: ci
        id: ci
        shell: pwsh
        run: npm ci

      - name: build
        id: build
        shell: pwsh
        run: |
          npm run build

      - name: deploy
        id: deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          BRANCH: master
          FOLDER: dist/resume
