name: release

on:
  release:
    types: [published]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      
jobs:
  release:
    runs-on: ubuntu-latest    
      
    steps:
      - name: download
        id: download
        shell: pwsh 
        run: |
          $releaseUrl = "https://api.github.com/repos/$env:GITHUB_REPOSITORY/releases/$($env:GITHUB_REF.Replace('refs/', ''))"
          $gitHubRelease = (Invoke-WebRequest -Uri $releaseUrl -Method Get -ContentType 'application/json' -Headers @{"Authorization" = "Bearer $env:GITHUB_TOKEN"}).Content | ConvertFrom-Json
          $gitHubRelease.assets | % {
            Invoke-WebRequest -Uri $_.browser_download_url -OutFile $_.name
            Expand-Archive -LiteralPath $_.name -DestinationPath $_.name.Split(".")[0]
          }

      - name: deploy
        id: deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          BRANCH: master
          FOLDER: resume
